# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install hexo-cli -g
    - run: rm -rf node_modules && npm install --force
    - run: hexo clean
    - run: hexo generate
    - name: Clone Github Repo Action
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        # Repository Owner
        owner: chi-bin
        # Repository name
        repository: https://github.com/chi-bin/chi-bin.github.io.git
        access-token: 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
